providers:
  file:
    filename: /etc/traefik/dynamic.yaml

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG
  filePath: "/etc/traefik/traefic.log"

accessLog:
  filePath: "/etc/traefik/access.log"